import Head from 'next/head'
import React from 'react'

type Props = {
    children: React.ReactNode
}

const Layout = ({ children }: Props) => {
    return (
        <>
            <Head>
                <title>RatePunk</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* navbar */}
            <header>
                <div className="container">
                    xgadg
                </div>
            </header>
                {children}
            <footer>
                <div className="container">asgag</div>
            </footer>
        </>
    )
}

export default Layout;