import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.scss'

type Props = {
    children: React.ReactNode
}

const Layout = ({ children }: Props) => {
    return (
        <>
            <Head>
                <title>RatePunk</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* navbar */}
            <main className={styles.main}>
                {children}
            </main>
            <footer className={styles.footer}>
                <div className={styles.container}>asgag</div>
            </footer>
        </>
    )
}

export default Layout;